### PR TITLE
Unit tests

### LINKED ISSUE #10: Rspec: Before & After Concept
This is valid.

It's also an opportunity to introduce two new RSpec concepts.

**1. Before and After**

```ruby
# Our SomeClass requires the name to be unique
RSpec.describe SomeClass do
  let(:instance_1) { SomeClass.create(name: 'a') }
  let(:instance_2) { SomeClass.create(name: 'a') }

  # a before block is used to setup things needed before a test is run.
  # They increase readability of tests.
  before { instance_1 } # this will instantiate the variable

  # P.S. Take a look at before. It's just Ruby. It's an instance method that accepts no args and a block (like all Ruby methods accept a block). Then Rspec ensures it's called before each `it` in a scope.
  # Gems can often seem like another language (and with their DSL they almost are from one perspective). But in truth it's Ruby all the way down.
  
  it 'must have unique title' do
    expect(instance_2).to_not be_valid
  end

  # you can also use after blocks to do stuff after. Same idea, otherside. I rarely (never??) need these.
  after {}
end
```

**let!()**
  
  Our example above is simple. The `before` block contains one statement, to instantiate the instance of the class.

This use is common enough that RSpec provides a shorthand.

```ruby
# Our SomeClass requires the name to be unique
RSpec.describe SomeClass do
  # the ! bangs it up.
  # Which is to say, is ensures the variable is instantiated (the statement is evaluated) before every test in the current scope.
  # instance_1 will always be made.
  let!(:instance_1) { SomeClass.create(name: 'a') }
  let(:instance_2) { SomeClass.create(name: 'a') }
  
  it 'must have unique title' do
    expect(instance_2).to_not be_valid
  end
end
```

Play around with these, pick one to use (sticking with your current approach is one of the options).

_Originally posted by @patrickquigley102 in https://github.com/awalsh3/books/pull/7#discussion_r1171360932_

### LINKED ISSUE #11: Learn Rails 6. Unit tests for the Books endpoint.
# Request Spec

This is the highest level unit test. 

Unit tests because they'll all run within a single process, no network requests elsewhere. We do rely on a Database though but that's fine, Rails + the SQL DB are so coupled together we should test them in the unit tests.

Highest level because they test a Rails application from an outside perspective I.E http request in http response out. Hence the name, request spec.

I like to organise them like so (I'm giving you this so you can focus on learning the tests, convention over configuration as they say in Rails).

```
app/
  controllers/
    books_controller.rb # imagine it has an index and delete action
spec/
  controllers/
    books_controller/ # one file per action
      index_spec.rb
      delete_spec.rb
```

## High level unit tests

As mentioned above these types of tests are able to test the full Rails stack.

Http request - http response.

That includes testing our routes, controllers and models (and views if we had any, as the response would contain HTML in the HTTP response).

## Further reading.

- https://rubyyagi.com/rspec-request-spec/
- https://dev.to/kevinluo201/introduce-rspec-request-spec-4pbl
- https://medium.com/just-tech/rspec-controller-or-request-specs-d93ef563ef11

Both of those blog posts contain concepts we're not looking at right now. Focus on what your controller does and ignore anything else (we're not using Devise, Capybara etc and we don't want to use controller tests).

## Need more help?

Let me know (including sharing what you have in a branch) if you need more help. I can provide a structure of the request file to help combine this new test type and the `before` and `let` concepts we've visited so far.

### LINKED ISSUE #14: Learn Rails 7. Testing an endpoint's range of responses.
### The story so far.

In the previous issue you authored unit tests, of the request type, for the books endpoint.

Those [tests](https://github.com/awalsh3/books/pull/12/files) (not merged at time of writing, start this after it's merged) test the happy path. 

They test when everything goes well. Books exist and they're successfully returned in the response.

### Purpose of this ticket.

We'd like to test unhappy paths!

We want to test our known failures, the ways we can predict this endpoint will behave. We want to test that behavior is as expected now and in the future.

What are these scenarios? There is not many.

To answer that question study the books controller. Look for ways it can fail. 

What does it need to be happy? What happens if it doesn't have that?

If you get stuck there is a hint below.

---

<details>
  <summary>Spoiler. Ways I can think the endpoint would fail. </summary>

1.   There are no books

That is it I think with our current code :joy: We're ignoring exceptions for now (next issue's concept to learn).

Plus our application is simple currently. As we add more over features we'd have more ways to fail. For example is we added authentication to the endpoint that that could fail. We'll be revisiting this again in the future!

</details>

### Expectations.

- Write unit tests only. We're documenting the existing behavior in our tests here, not changing the behavior.

### PR DESCRIPTION
**Pull request by awalsh3**
Hi Paddy, could you let me know if I am on the right track here? And if so I'll refactor to include the before and let concepts we've visited so far. Thanks!

### CODE REVIEW

**Comment by patrickquigley102** [comment]
Hey Annie.

Nice work, you're on the right track. :slightly_smiling_face:

**Comment by awalsh3** [comment]
I was getting confused by the various terms used. I've written it out here for my reference.

The eight types of RSpec specs
The RSpec library offers a lot of different spec types.

**Model specs
System specs/feature specs*
Request specs/controller specs***
Helper specs
View specs
Routing specs
Mailer specs
Job specs
There are two lines with asterisks. These are cases where the RSpec team decreed one spec type obsolete and replaced it with a new type.

File: spec/controllers/books_controller/index_spec.rb [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+    let(:title) { 'The Hobbit' }
+    let(:description) { 'the unforgettable story of Bilbo, a peace-loving hobbit, who embarks on a strange and magical adventure. A timeless classic.' }
+    let(:word_count) { 250_000 }
+    let(:rating) { 4 }
+
+    it 'returns http success' do
+      get api_v1_books_path
+      expect(response).to have_http_status(:success)
+      expect(response.status).to eq(200)
+      expect(json[:data].size).to eq(1)
```
Comment (patrickquigley102) [inline spec/controllers/books_controller/index_spec.rb:25]: Here we're asserting some pretty granular level of details in the response.

Which makes the tests more expensive to maintain over time. If we extended the features/tests at some point it's likely these lines would need editing. As it may know return a different book first etc.

This is an art judging this kind of thing. Judging how much detail to test.

How can we make these assertions less granular and more generic? 

Can we test the structure of the response without testing the book details themselves?

File: spec/controllers/books_controller/index_spec.rb [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+      Book.create(
+        author_name: 'George R.R. Martin',
+        title: 'A Game of Thrones',
+        description: 'Fight to the death of mupltiple families hungry for power',
+        rating: 5,
+        word_count: 600_000
+      )
+      get api_v1_books_path
+      expect(json[:data].size).to eq(2)
+      expect(json[:data][0][:attributes][:title]).to eq('The Hobbit')
```
Comment (patrickquigley102) [inline spec/controllers/books_controller/index_spec.rb]: Every test has a maintenance cost in your codebase.

Lines 50 & 51 here. Do we need them?

In my opinion line 49 makes lines 50 & 51 redundant. We don't care about the titles, just that two are made for the test and 2 are returned in the http response.

Keen to hear your thoughts!

File: spec/rails_helper.rb [hunk 3]
```diff
@@ -38,6 +38,8 @@
   # instead of true.
   config.use_transactional_fixtures = true
 
+  # config.include Rails.application.routes.url_helpers, type: :request
```
Comment (patrickquigley102) [inline spec/rails_helper.rb]: Why have you added this comment?

Not against it if there is a rationale.

**Review by patrickquigley102 — CHANGES_REQUESTED** [review]
Good job. I've left some Qs to ponder/action code changes.

File: spec/controllers/books_controller/index_spec.rb (hunk 1 above)
Comment (awalsh3) [reply spec/controllers/books_controller/index_spec.rb:25]: Great point. It's good practice for me to work on the app as if it will be maintained over time! Here since we are just testing the response we only need to test if something, anything (as long as it's a book) is returned back? So we would be only testing attributes of the response like status and meta and not the content of the response?

File: spec/controllers/books_controller/index_spec.rb (hunk 2 above)
Comment (awalsh3) [reply spec/controllers/books_controller/index_spec.rb]: No we don't need them! Here we still only need to test something has been returned... in this case 2 books instead of 1 (or all books) and not the content of the books themselves (what's in the object?)

File: spec/rails_helper.rb (hunk 3 above)
Comment (awalsh3) [reply spec/rails_helper.rb]: I believe this was part of an original attempt at the routes for the API. Commented out when I realized I didn't need it but it should be removed!

File: spec/controllers/books_controller/index_spec.rb (hunk 1 above)
Comment (patrickquigley102) [reply spec/controllers/books_controller/index_spec.rb:25]: Yeah just that. Nice one!

File: spec/controllers/books_controller/index_spec.rb (hunk 2 above)
Comment (patrickquigley102) [reply spec/controllers/books_controller/index_spec.rb]: Nice. As you say. Similar topic to this one: https://github.com/awalsh3/books/pull/12#discussion_r1216411991

File: spec/rails_helper.rb (hunk 3 above)
Comment (patrickquigley102) [reply spec/rails_helper.rb]: Very easy for things like this to slip through, all good.

**Review by patrickquigley102 — APPROVED** [review]
LGTM

File: spec/controllers/books_controller/index_spec.rb (hunk 1 above)
Comment (awalsh3) [reply spec/controllers/books_controller/index_spec.rb:25]: pick one Annie
