### PR TITLE
Exceptions rescue

### LINKED ISSUE #17: Learn Rails 9. Exceptions 2.
# A more realistic Exception example.

We're going to use a useful example now that is very common design pattern in the Rails community.

We need to modify our Books controller first to do use this pattern, called a Service Object.

Blog post on common design patterns for extra reading: https://rubyhero.dev/rails-design-patterns-the-big-picture

## Use a Service Object in Controller.

I will be fairly prescriptive here, let me know if it was too prescriptive and therefore easy.

Our controller is currently responsible for: fetching all books, serializing them and returning them as serialized JSON.

Lets make a Service Object that serializes ActiveRecord Books into JSON.

The controller will then look like.

```ruby
module Api
  module V1
    class BooksController < ApplicationController
      def index
        render json: serialized_books
      end

      private

      def serialized_books
        BookSerializer.serialize(books) # returns a json formatted string, as that is what serialization is in this context.
      end

      def books
        Books.all
      end
    end
  end
end
```

Lets split the work down into nice & easy chunks.

1. Write a PR that creates a BookSerializer and it's unit tests. This PR will contain no changes to the controller. The unit tests are the low level kind, that follow black box testing approach followed for any plain old Ruby object.
2. Write a PR that uses this new class in the controller. Hopefully our controller tests, of the higher level request spec type, will require no changes (it's okay if they do!). Read those controller tests over, you'll be able to see they're still testing our full stack here and give us confidence.

## Now for exceptions

Now we can explore the value of Exceptions in a very real way. Where as our first Exception ticket was an introduction to the concept.

How could this controller fail? Look & think about it before reading on.

---

Our serializer could return an expected response or, could :boom: and raise an exception. Lets explore the latter.

RSpec is awesome and provides first class support for stubbing (replacing) the response of any class with whatever we like. In our case it's an exception.

```ruby
# Tell RSpec what behaviour is allowed, what is being stubbed.
# RSpec will now raise this error when this class is called, but only in the relevant scope set in RSpec.
allow(BookSerializer).to receive(:serialize).and_raise(StandardError)
```

More here: https://stackoverflow.com/a/32355398/4654311

1. Write a PR that tests the context. When the serializer does not return a JSON string but, instead raises an exception. This will be a `context` block in the `index_spec.rb` file, part of the request level unit testing.
2. Now amend the controller (same PR, listing steps for good learning) code itself to rescue the error and return a better response. What is the most useful thing we can return to our consumer of the API in this scenario?

### PR DESCRIPTION
**Pull request by awalsh3**
- When the serializer does not return a JSON string but, instead raises an exception. 
- Amended the controller to rescue the error. 
- Returns a 500 response.

### CODE REVIEW

File: app/controllers/api/v1/books_controller.rb [hunk 1]
```diff
@@ -3,6 +3,8 @@ module V1
     class BooksController < ApplicationController
       def index
         render json: serialized_books
+      rescue StandardError
```
Comment (patrickquigley102) [inline app/controllers/api/v1/books_controller.rb:6]: This is perfect as is!

If we added more controllers to this application we could move the rescue to the ApplicationController, to keep things DRY.

But adding here whilst there is one controller is perfect imo. I like to DRY on the third repetition. [To avoid this warning from Sandi Metz.](https://sandimetz.com/blog/2016/1/20/the-wrong-abstraction)

**Review by patrickquigley102 — APPROVED** [review]
Lovely as is. Nice work.

Added a comment that's sharing knowledge. No changes required.

File: app/controllers/api/v1/books_controller.rb (hunk 1 above)
Comment (awalsh3) [reply app/controllers/api/v1/books_controller.rb:6]: This is great --- "When they altered their point of view from "I must preserve our investment in this code" to "This code made sense for a while, but perhaps we've learned all we can from it," and gave themselves permission to re-think their abstractions in light of current requirements, everything got easier. Once they inlined the code, the path forward became obvious, and adding new features become faster and easier."

**Comment by awalsh3** [comment]
I will wait to merge this until after we next meet so I can use it as a reference to explain line by line what is happening?

**Comment by patrickquigley102** [comment]
Merge away! The diff will still be accessible after a merge :smile:
